### ISSUE TITLE
Support/document kind clusters

### ISSUE THREAD

**Issue by howardjohn** [rancher/kim#49]
I tried this out on https://kind.sigs.k8s.io/.

I had to pass `--containerd-socket=/run/containerd/containerd.sock` on install. I then had to modified to mount `/var/lib/containerd` on the Daemonset. Once I did that, things worked great.

**Comment by dweomer** [comment]
@howardjohn I've got this working via #55 with some node inspection to detect what kind of containerd we are running against and adjust the socket and storage parent/path mount locations.
