### ISSUE TITLE
kim doesn't seem to support multiple files in KUBECONFIG

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [rancher/kim#87]
Hello, 
I'm encountering an error where kim doesn't work with multiple kubeconfigs. My kubeconfig setup has a single kubeconfig per cluster I access. Kubectl supports this natively, using a colon `:` to parse the configs in order, very similar to the workings of the PATH variable. This is a breaking issue for me, and I'm unable to use kim to run commands.

```
 ajones@ajones  ~  kim pull alpine
Error: stat /Users/ajones/.kube/config:/Users/ajones/code/k8s-bootstrapping/environments/dev/kubeconfig_agari-dev-k8s:/Users/ajones/code/k8s-bootstrapping/environments/stage/kubeconfig_agari-stage-k8s:/Users/ajones/code/k8s-bootstrapping/environments/prod/kubeconfig_agari-prod-k8s:/Users/ajones/code/k8s-bootstrapping/environments/euc1-prod/kubeconfig_agari-euc1-prod-k8s:/Users/ajones/code/k8s-bootstrapping/environments/ops/kubeconfig_agari-ops-k8s:/Users/ajones/code/k8s-bootstrapping/environments/sensors/kubeconfig_agari-sensors-k8s: no such file or directory
```

**Comment by dweomer** [comment]
Hi @AlexMichaelJonesNC,

It looks as if you are likely using a version of KIM that is older than https://github.com/rancher/kim/releases/tag/v0.1.0-beta.7 which should have fixed this issue.

See also:
- #81

**Comment by AlexMichaelJonesNC** [comment]
that would be it, I just started using rancher desktop and 0.21 current has beta6 as the version.
